account_id = "3e3e32e8bdbb4d02642cb92d61e18b85"
workers_dev = true

name = "tiers"
main = "src/index.tsx"
compatibility_date = "2024-01-17"

[[r2_buckets]]
binding = "R2_TIERS"
bucket_name = "tiers"
preview_bucket_name = "tiers"